// File generated from our OpenAPI spec by Stainless. See CONTRIBUTING.md for details.

export { type ClientOptions, Velix as default, Velix } from "./client";
export { APIPromise } from "./core/api-promise";
export {
	APIConnectionError,
	APIConnectionTimeoutError,
	APIError,
	APIUserAbortError,
	AuthenticationError,
	BadRequestError,
	ConflictError,
	InternalServerError,
	NotFoundError,
	PermissionDeniedError,
	RateLimitError,
	VelixError,
	UnprocessableEntityError,
} from "./core/error";
export { toFile, type Uploadable } from "./core/uploads";


export {
	type AgentListParams,
	type AgentListResponse,
	type AgentRunParams,
	type AgentRunResult,
	Agents,
	type Automation,
	type AutomationCreateParams,
	type AutomationListResponse,
	type AutomationLogsParams,
	type AutomationLogsResponse,
	type AutomationRun,
	type AutomationRunDispatched,
	Automations,
	type AutomationSummary,
	type AutomationUpdateParams,
	type Host,
	type HostAgentConfig,
	type HostListResponse,
	Hosts,
	type HostWorkspace,
	type Project,
	type ProjectListResponse,
	Projects,
	type PromptTransport,
	type Task,
	type TaskCreateParams,
	type TaskListItem,
	type TaskListParams,
	type TaskListResponse,
	Tasks,
	type TaskUpdateParams,
	type Workspace,
	type WorkspaceAgentLaunch,
	type WorkspaceCreateAgentResult,
	type WorkspaceCreateParams,
	type WorkspaceCreateResult,
	type WorkspaceDeleteResult,
	type WorkspaceListParams,
	type WorkspaceListResponse,
	Workspaces,
} from "./resources/index";
